version: '3.7'

services:
  django:
    build:
    context: .
    ports:
      - "8000:8000"
    volumes:
      - ./COMMBANK:/commbank

    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    
    environment:
      DJANGO_SETTINGS_MODULE: "your_project.settings.development"
      DEBUG: "True"
    # Links the Django service to the database service
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    # Optional volume to persist database data
    # volumes:
    #   - db_data:/var/lib/mysql

# volumes:
#   db_data:
