# Generated by Django 5.0 on 2024-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
