# Generated by Django 5.0 on 2024-02-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_currentaccount_user_alter_savingsaccount_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.currentaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='accounts.savingsaccount'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='current_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='accounts.currentaccount'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='savings_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='accounts.savingsaccount'),
        ),
    ]
