# Generated by Django 5.0 on 2024-02-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transaction_receiver_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_account',
            new_name='cuurent_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_account',
            new_name='savings_account',
        ),
    ]
