# Generated by Django 5.0 on 2024-02-22 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_receiver_account_transaction_cuurent_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSB_number', models.CharField(max_length=6, unique=True)),
                ('branch_city', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.CharField(max_length=512)),
                ('branch_manager', models.CharField(max_length=255)),
                ('branch_phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cuurent_account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='current_account',
        ),
        migrations.RemoveField(
            model_name='savingsaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='savings_account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='savings_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='BSB_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit'), ('Transfer', 'Transfer')], default='Withdraw', max_length=10),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.IntegerField(default=1000, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentAccount',
        ),
        migrations.DeleteModel(
            name='SavingsAccount',
        ),
    ]
