# Generated by Django 5.0 on 2024-02-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_branchinfo_remove_transaction_cuurent_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='1000', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
