# Generated by Django 5.0 on 2024-03-15 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_branchinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit'), ('Sent', 'Sent'), ('Received', 'Received')], default='Withdraw', max_length=10),
        ),
    ]
