# Generated by Django 5.0 on 2024-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_transaction_receiver_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_account_number',
            new_name='second_account_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('SENT', 'Sent'), ('RECEIVED', 'Received')], max_length=10),
        ),
    ]
