# Generated by Django 5.0 on 2024-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_receiver_account_number_transaction_second_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('SENT', 'Sent'), ('RECEIVED', 'Received')], max_length=10),
        ),
    ]
